### ISSUE TITLE
Which version?

### ISSUE THREAD

**Issue by zhangyoufu** [sharkwouter/laser-kombat-love#1]
I think there're 2 versions available on Internet Archive:
* [1999-08-11](https://web.archive.org/web/20000816000822/www.olympus.net/personal/dewey/laser/laser_kombat_setup.exe)
* [2001-10-06](https://web.archive.org/web/20011031103140/www.olympus.net/personal/dewey/laser/laser_kombat_setup.exe)

So which version did you reverse-engineered?

**Comment by sharkwouter** [comment]
This was based on the 1.0 beta, which is the last version which was made available. The original author has since released the source code for the 1.0 alpha, though, which is available here: https://gitlab.com/ddewey/laserkombat/-/tree/master

I'm trying to port this code to modern operating systems and a newer version of C++ at the moment, but it has been a slow process so far. I have the code here: https://github.com/sharkwouter/laserkombat

I have some tiles loading and the game starting. I have an input system, but nothing related to movement has been implemented yet and only a couple of tiles load.

**Comment by zhangyoufu** [comment]
Thank you for the information.
